[user]
name = "Simeon Romanov"
email = "archeoss@proton.me"

[ui]

[merge-tools.mergiraf]
program = "mergiraf"
merge-args = ["merge", "$base", "$left", "$right", "-o", "$output", "-l", "$marker_length", "--fast"]
merge-conflict-exit-codes = [1]
conflict-marker-style = "git"
